name: Unittest
on:
    push:
        branches: [ master ]

jobs:
    publish:
        if: github.repository == 'phamleduy04/agentbot-master'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: yarn install --frozen-lockfile
            - run: npm run docker-ci
              env: 
                TOKEN: ${{ secrets.TOKEN }}
                TESTBOTTOKEN: ${{ secrets.TESTBOTTOKEN }}
                CHANNELID: ${{ secrets.CHANNELID }}

